[server]
host = "127.0.0.1"
port = 7590

[database]
host = "localhost"
port = 5432
database = "ayiou"
user = "postgres"
password = ""
table_prefix = ""
max_connections = 10
connect_timeout = 30

[jwt]
secret = "your-secret-key-change-in-production"
expires_in_hours = 24

[cache]
ttl_seconds = 3600
max_entries = 10000

[app]
default_domain = "https://ayiou.com"
short_code_length = 6
max_custom_length = 20
rate_limit_per_minute = 100
